config/routes.rb
 

  

  Rails.application.routes.draw do


    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'

    mount Ckeditor::Engine => '/ckeditor'
   
   get 'login', to: redirect('/auth/google_oauth2')
   get 'login' , to: redirect('/auth/github')
   get 'logout', to: 'sessions#destroy'
   get 'auth/:provider/callback', to: 'users/sessions#create_admin'
   get '/auth/github/callback' , to:'users/sessions#create_admin'
   get '/auth/facebook/callback' , to:'users/sessions#create_admin'
   get 'auth/failure', to: redirect('/')
      get 'password_resets/new'
  get 'password_resets/edit'


   root 'sessions#new'
   resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]



    namespace :api do 
      namespace :v1 do
        resources :sessions do
          collection do
            post :show_all_user 
            post :otp_admin
            post :create_users
            post :user_view
            delete :user_destroy
            post :block
            post :user_role_create
            post :user_role_update
            post :show_role
            delete :role_destroy
            post :content_create
            post :show_content
            delete :content_destroy
            post :create_action
            post :show_menu
            post :permission_management
            post :show_all_permission
            delete :permission_destroy
          end
        end
      end
    end




namespace :admins do 
  resources :admins do
    collection do
      post :user_role_update
      get :dashboard
      get :users
      get :static_content
      post :content_create
      get :show_content
      get :user_view
      get :block
      get :user_destroy
      get :content_destroy
      get :create_user
      post :create_users
      get :user_role
      post :user_role_create
      post :user_permission_create
      get :permission_management
      post :return_actions
      post :save_permission
      get :permission_destroy
      get :role_destroy
      get :menu_destroy
      get :content_edit
      post :content_update
      post :check_action
      post :check_menus_action
      
     end
    end
 resources :sessions do
      collection do
       get :otp
       get :destroy
       post :otp_admin
       get :signout
      end
    end 
end


namespace :users do 
  resources :users do
    collection do 
     get :dashboard
     get :show
     get :destroy
     post :check_email
     get :dashboard
      get :users
      get :static_content
      post :content_create
      get :show_content
      get :user_view
      get :block
      get :user_destroy
      get :content_destroy
      get :create_user
      post :create_users
      get :user_role
      post :user_role_create
      post :user_permission_create
      get :permission_management
      post :return_actions
      post :save_permission
      get :permission_destroy
      get :role_destroy
      get :menu_destroy
      get :content_edit
      post :content_update
      post :check_action
      post :check_menus_action


     end
    end

      resources :sessions do
      collection do
       post :otp
       post :otp_user
       get :destroy
      end
    end
    resources :password_resets do
      collection do
        post :create
        get :new
        get :edit
      end
    end
  end



end
     
   

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < ApplicationController

	before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
 before_action :check_expiration, only: [:edit, :update]

  def new

  end



def create

    @user = User.find_by(email: params[:password_reset][:email])
    if @user
      @user.create_reset_digest
    	UserMailer.with(user: @user).password_reset.deliver_now 
      flash[:notice] = "Email sent with password reset instructions"
      redirect_to new_users_session_path
    else
      flash.now[:notice] = "Email address not found"
      render new_users_password_reset_path
      # redirect_to login_path  
  end
end



  def edit
  end

 def update

 	@user = User.find_by(email: params[:email])
     @user.update!(password: params[:User][:password] , password_confirmation: params[:User][:password_confirmation] )    
    	
       # @user.update_attributes(reset_digest: nil)
      flash[:notice] = "Password has been reset."
      redirect_to new_users_session_path
   
end





  private

  def user_params
     params.permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.authenticated?(:reset, params[:id]))
        redirect_to new_users_session_path
      end
    end


def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_users_password_reset_url
      end
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController

  
before_action :require_login, except: [:new ,:create ,:otp,:otp_user , :create_admin]
layout 'login_admin'
before_action :status_check, except: [:new , :create,:otp ,:otp_user]


  def new
    # binding.pry
      @captcha = rand 1000..9999
      session[:captcha] = @captcha
      redirect_to users_user_path(id: current_user.id) if logged_in? 

  end


def show

end
  


   def create
   # binding.pry 
     if session[:captcha] == params[:session][:captcha].to_i
      @user = User.find_by(email: params[:session][:email]) 

       if @user && @user.authenticate(params[:session][:password]) && @user.status==false
   
       @user= User.find_by(email: params[:session][:email])

       otp = rand 1000..9999
       @user.update(onetimepassword: otp)
       
       ContactJob.perform_later(@user) 
       render 'users/sessions/otp'


       
              elsif @user && @user.authenticate(params[:session][:password]) && @user.status==true
          flash.now[:notice] = "you are blocked by Admin"
           render 'users/sessions/new'
          
          else
          flash.now[:notice] = "Wrong email and password"
        render 'users/sessions/new'
             end
        
    else
      flash.now[:notice] = "Invalid captcha"
      @captcha = rand 1000..9999
      session[:captcha] = @captcha
           render 'users/sessions/new'
     
end

end




def create_admin
   @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
      session[:user_id] = @user.id
      WelcomeJob.perform_later
      redirect_to dashboard_users_users_path(id: @user.id)
end


def otp
 @user = User.find_by(id: params[:id])  
end


  def otp_user
      # binding.pry 
      @user = User.find_by(id: params[:id])
  if @user && @user.onetimepassword == params[:session][:otp].to_i && @user.status==false
	
	session[:user_id] = @user.id
	redirect_to dashboard_users_users_path(id: @user.id)
  		 	
  	else
  		flash.now[:notice] = "Wrong otp"
      redirect_to otp_users_sessions_path(id: @user.id)
  end
  

end



  def destroy

    session.delete(:user_id )
     session[:user_id] = nil

    flash[:notice] = "You have logged out"  
    redirect_to new_users_session_path
  end


private
def require_login 
 
    unless logged_in? 
      flash[:notice] = "You must be logged in to access this section"
      redirect_to new_users_session_path
    end
  
  end

def status_check
   if current_user.status == true
    flash[:notice] = "You are blocked by admin"
    redirect_to new_users_session_path
end
end


end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

before_action :require_login, except: [:new , :create ,:check_email ,:return_actions,:check_action]
# before_action :check_permission , except: [:new , :create]
before_action :set_current_ip , except: [:new , :create ]
before_action :status_check, except: [:new , :create ]
layout 'user'


def new
  # binding.pry
@user = User.new

render :layout => false
  end


	def show
  #    # binding.pry
  # @user = current_user 
  #    @contentss = []
  #     StaticContent.all.each do |content|
 
  #           if (content.start_date == nil || content.end_date == nil) || (content&.start_date < DateTime.now  && DateTime.now < content&.end_date)

     
  #               @contentss << content
  #           # else
  #             # latest_content = StaticContent.find_by(:end_date => Time.zone.now < content.end_date)
  #             # content.update(old_content: content.latest_content,latest_content: "")
  #             # latest_content.delete
  #           end
  #         end	 	
  end



	def create
    
  	@user = User.new(user_params)
     if @user.save

     	WelcomeJob.perform_later(@user)
      flash[:notice] = "Sucess"
     redirect_to new_users_session_path 
    else
      redirect_to new_users_user_path
      
    end

		end


def edit
  # binding.pry
  @user = User.find_by(id: params[:id])
end

def update
  # binding.pry
  @user = User.find_by(id: params[:id])
 
  if @user.update(user_params)
    redirect_to dashboard_users_users_path
  else
    render 'users/users/edit'
  end

  end


  def destroy
    # binding.pry
  @user = User.find_by(id: params[:id])
  @user.destroy
 
  redirect_to dashboard_users_users_path
  end



  def check_email
    # binding.pry
    email_found = User.find_by(email: params[:email]) #Whatever your logic is to find duplicate emails
    message = email_found ? "ERROR" : "SUCCESS"
    render json: {message: message}
  end



def create_user
  @user=User.new
   @user = current_user

end

def create_users
@user = User.new(user_params)
     if @user.save
      
     redirect_to  users_users_users_path
    else

      redirect_to create_user_users_users_path
      
    end 
end
 
def users
  if logged_in_a? 
  @user = current_user
  @users = User.all.order("created_at desc").paginate(:page => params[:page], :per_page => 5)

else
redirect_to new_users_session_path
end
end



def dashboard
 if  current_user.status==false
   @user = current_user
   @contentss = []
      StaticContent.all.each do |content|
 
            if (content.start_date == nil || content.end_date == nil) || (content&.start_date < DateTime.now  && DateTime.now < content&.end_date)

     
                @contentss << content
            # else
              # latest_content = StaticContent.find_by(:end_date => Time.zone.now < content.end_date)
              # content.update(old_content: content.latest_content,latest_content: "")
              # latest_content.delete
            end
          end 
          else
          redirect_to new_users_session_path
          flash[:notice] = "You are blocked by admin"
        end
end

def static_content
   @user = current_user
end

def content_create
   @user = current_user
   @content = StaticContent.create(content_params)
   redirect_to show_content_users_users_path
end

def user_view
  @user = current_user
  @user_view = User.find_by(id: params[:id])
end

def show_content

 @user = current_user
@contents = StaticContent.order("created_at desc").paginate(:page => params[:page], :per_page => 5)


end


def user_role_update
# binding.pry
 @user = current_user
unless params[:session][:user_role_id] == ""
@user = User.find_by(id: params[:id])
  @user.update(user_role_id: params[:session][:user_role_id])
  redirect_to users_users_users_path(current_user)
end
end


def user_role
 @user = current_user

end

def user_role_create
  # binding.pry
 @user = current_user

  @role = UserRole.create(name: params[:session][:name]) unless params[:session][:name]==""
  @menu = Menu.create(menu: params[:session][:menu]) unless params[:session][:menu] ==""
   redirect_to  user_role_users_users_path
end

def user_permission_create
   # binding.pry
 @user = current_user
   
@menu =  Menu.find_by(id: params[:session][:menu_id]) 
 @menu.actions.create(action: params[:session][:action]) 
   
   redirect_to  user_role_users_users_path
end


def block
  # binding.pry
   
  @user = User.find_by(id: params[:id])
      if @user.status == false  
          @user.update(status:true)

          session[:user_id] = nil

      else
          @user.update(status:false)
      end
      redirect_to  users_users_users_path(current_user)
end


def user_destroy
    # binding.pry
  @user = User.find_by(id: params[:id])
  @user.destroy
 
  redirect_to users_users_users_path
  end

def content_destroy
@content = StaticContent.find_by(id: params[:id])
@content.destroy
redirect_to show_content_users_users_path
end

def permission_management
 @user = current_user
 @UserRoles = UserRole.all

end

def return_actions
          # binding.pry
        @menu = Menu.find(params[:code])
        @actions = @menu.actions.pluck(:action)
        render json: {fields: @actions}
    
    end


def save_permission
# binding.pry
# @role = UserRole.find_by(id:params[:permission][:role]).name
@roles = UserRole.find_by(id: params[:permission][:role])
a = Menu.find_by(id:params[:permission][:menus]).id
@action = @roles.permissions.create(menu_id:a,permission: params[:permission][:action])
 redirect_to permission_management_admins_admins_path 
end




def permission_destroy
  # binding.pry
@permission = Permission.find_by(id: params[:id])
@permission.destroy

redirect_to permission_management_admins_admins_path
end


def role_destroy
@role = UserRole.find_by(id: params[:id])
@role.destroy
redirect_to user_role_users_users_path
end

def menu_destroy
@menu = Menu.find_by(id: params[:id])
@menu.destroy
redirect_to user_role_users_users_path
end
def content_edit
  # binding.pry
 @user = current_user
 @content = StaticContent.find_by(id: params[:id]) 
end


def content_update
  # binding.pry
  @content = StaticContent.find_by(id: params[:id])
  @content.update(content_update_params)
redirect_to show_content_users_users_path
end
 def check_action
    # binding.pry
    a = UserRole.find_by(id:params[:roles]).permissions #Whatever your logic is to find duplicate emails
     b = a.pluck(:permission)
     c = b.include? params[:actions] 
    message = c ? "ERROR" : "SUCCESS"

    render json: {message: message}
  end


private

  def user_params
    params.require(:user).permit(:name , :email , :phone , :password , :password_confirmation,:avatar,:otp)
  end


def content_params
    params.require(:session).permit(:title,:latest_content,:start_date,:end_date)
  end


def content_update_params
    params.require(:content).permit(:title,:latest_content,:start_date,:end_date)
  end

 def user_params
    params.require(:user).permit(:name , :email , :phone , :password , :password_confirmation,:avatar,:user_role_id , :remote_ip,:user_agent)
  end

def require_login 
   unless logged_in?
      flash[:notice] = "You must be logged in to access this section"
      redirect_to new_users_session_path
    end
  end


def status_check
   if current_user.status == true
    flash[:notice] = "You are blocked by admin"
    redirect_to new_users_session_path
end
end

def set_current_ip
  # binding.pry
  a = User.find_by(id: current_user.id)
  a.update(remote_ip: request.ip)
   a.update(user_agent: request.env['HTTP_USER_AGENT'])
end
def content_update_params
   params.require(:content).permit(:title,:latest_content,:start_date,:end_date)
 end


end

	
 

 
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/users/content_edit.html.erb
<h1>Static Content Management</h1>

<p class="box box-primary"></p>



<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>

	<%=  form_for :content, url: content_update_users_users_path(id: @content.id) ,method: :post, local: true do |b| %>
   <%= b.label :Title %> 
   <%= b.text_field :title , value: @content.title%><br><br> 
  

   <%= b.label :Content %> 
<%= b.text_area :latest_content, :class => 'ckeditor' , value: @content.latest_content%><br>
   <%= b.label :"Start Date" %> 
   &nbsp;

 <%= b.date_field :start_date ,value: @content&.start_date && l(@content&.start_date&.to_date) %>

  <%= b.label :"End Date"  , style: "margin: 0 0 0 400px;"%>
  
  <%= b.date_field :end_date , value: @content&.end_date && l(@content&.end_date&.to_date ) , style: "margin: 0 0 0 20px;" %><br>


	<%= b.submit :save ,class:"btn btn-success",  style: "margin: 0px 0px -200px 500px;" %>
<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  show_content_users_users_path, class:"btn btn-primary"  ,title: "Back"  ,  style: "margin: 0px 0px -200px 50px;" %>
	<%end%>



    

app/views/users/users/create_user.html.erb
<h1>Add User</h1>

<%= flash[:notice] %>

<%= form_with scope: :user, url: create_users_users_users_path,:html=>{id: "first"},local: true  do |form| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



 <p>
    <%= form.label :Name %>
    <%= form.text_field :name ,placeholder: 'Your name here' %>
  </p>
 
 <p>
    <%= form.label :Email %>
    <%= form.email_field  :email ,placeholder: 'Your email here'%>
 
  </p>
 
<p>
    <%= form.label :Phone %>
    <%= form.text_field  :phone , placeholder: 'Your phone here'%>
 
  </p>
 


<p>
   <%= form.label :password %>
<%= form.password_field :password %>
</p>

<p>
   <%= form.label :Confirm_password %>
<%= form.password_field :password_confirmation %>
</p>


<p>
   <%= form.label :Role %>

  <%= form.collection_select :user_role_id, UserRole.order(:name), :id, :name,   include_blank: true %>
</p>

<p>
   <%= form.label :Profile %>
<%= form.file_field :avatar ,onchange: "readURL(this);"%>
</p>
 <div>
 <img id="blah" />
</div>


  <p>
    <%= form.submit "Signup"%>
  </p>

  <%end%>

<script type="text/javascript">

function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(150);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script> 
<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  users_admins_admins_path, class:"btn btn-primary"  ,title: "Back" %>

app/views/users/users/permission_management.html.erb
  <h1>Permission Management</h1>
<p class="box box-primary"></p>


 <%=  form_for :permission,html: { onsubmit: "return myFunction1(this);" }, url: save_permission_users_users_path ,method: :post, local: true do |b| %>


<%= b.label :Role %>
<%= b.collection_select :role, UserRole.all, :id, :name,  :prompt => 'Select',required: true %>

<%= b.label :menu %>
<%= b.select(:menus, Menu.all.order('created_at ASC').first(3).collect {|m| [m.menu, m.id]},{prompt: "Select"},{onchange: "myFunction(this);"}) %>



<%= b.label :action %>
<%= b.select :action, options_for_select([]),:prompt => 'Select' 	%>

<td><%= b.submit "Save" , class:"btn btn-primary"%></td>

<%end%>



 <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Role</th>
					<th>Menu</th>
				<!-- 	<th>Profile</th> -->
					<th>Actions</th>
					<th></th>

                  </tr>
                  <tr>
                    <%#@contents = [] unless @contents.present?%>

				<% Permission.all.each do |permission|%>
          <%#binding.pry%>
          <% unless permission.eql?(nil) %>
          <td><%= UserRole.find_by(id:permission.user_role_id).name%></td>
          <td><%= Menu.find_by(id:permission.menu_id).menu%></td>
          <td><%= permission.permission%></td>
           
          
          
<td><%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  permission_destroy_users_users_path(id: permission.id), class:"btn btn-danger"  ,title: "Delete" %> </td>
          

					</tr>
                


<%end%>
<%end%>


</table>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>




<script type="text/javascript">
  $('#session_menu_id').change(myFunction);
 function myFunction(input){
// debugger;
 var menu_id = input.value;
 code = {code: menu_id}
   
     if(menu_id == "")
     {
       $('#permission_action').empty();
     }
     else
     {
 $.ajax(
   {
     type: 'POST',
     url: "/admins/admins/return_actions",
     data: code,
     success: function(result){
       var new_options = result;
       var menuaction = $('#permission_action').empty();
   $.each(new_options, function(key,values) {
     $.each(values, function(index,value) {
     menuaction.append($("<option></option>").attr("value", value).text(value));
   });
   });

  // alert ("ffcng");
   }
});
}
 }
</script>



<script type="text/javascript">
// debugger;
function myFunction1(input){
  debugger;
 var role = input.elements[2].value;
 var menu = input.elements[3].value;
 var action = input.elements[4].value;
 actions = {actions: action}
 menus = {menus: menu}
 roles = {roles: role,actions: action}

       if((role == "") || (menu == "") || (action == ""))
     {
    alert("plz select all the filed");
    return false;
  }
  else
  {
    $.ajax({
  url: '/users/users/check_action',
  method: 'POST',
  data: roles,
    success: function(response){
    if(response && response.message=='ERROR'){
        alert("Permission already exists");
    }
}
});
        return false;

  }
}

  
</script>

app/views/users/users/show_content.html.erb
<h1>Static Content Management</h1>
<%= link_to '<em class="btn fa fa-plus-circle" aria-hidden="true"></em><span style="font-size:15px">Add New Content</style>'.html_safe,  static_content_users_users_path, class:"btn btn-sm btn-primary" ,title: "Add Content", style: "float:right;margin-top:-50px" %>
<p class="box box-primary"></p>



 

<div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Title</th>
					<th>Content</th>
					<th>Start Date</th>
					<th>End Date</th>
					<th>Action</th>

					
                  </tr>
                  <tr>
					<% @contents.each do |content|%>
					<% unless content.eql?(nil) %>
					<td><%= content.title %></td>
					<td><%= content.latest_content.html_safe%></td>
					<td><%= content.start_date%></td>
					<td><%= content.end_date%></td>

<td>
					<% if return_action_id("Edit") %>
<%= link_to '<em class="fa  fa-edit" aria-hidden="true"></em>'.html_safe,  content_edit_users_users_path(id: content.id), class:"btn btn-primary"  ,title: "Edit" %> 
  						<% end %>


					<% if return_action_id("Delete") %>
<%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  content_destroy_users_users_path(id: content.id), class:"btn btn-danger"  ,title: "Delete" %> 

  						<% end %></td>




					</tr>
                


<%end%>
<%end%>


</table>
<%= will_paginate @contents %>

</div>


  						
         				

app/views/users/users/user_role.html.erb
<h1>Create Role</h1>
<p class="box box-primary"></p>

<%=  form_for :session, url: user_role_create_users_users_path ,method: :post, local: true do |b| %>
	
    <%= b.label :Role %>

	<%=b.text_field :name , required:true%>
				
 <%#= b.label :Menu %>
<%#=b.text_field :menu %>

	<td><%= b.submit "Create" , class:"btn btn-primary"%></td>


	<%end%>

<h1>Create Actions for each menu</h1>
<p class="box box-primary"></p>

<%=  form_for :session,html: { onsubmit: "return myFunction(this);" }, url: user_permission_create_users_users_path ,method: :post, local: true do |b| %>

    <%= b.label :Menu %>

<%= b.collection_select :menu_id, Menu.all.order('created_at ASC').first(3), :id, :menu, {:include_blank => '-select-'}%>

    <%= b.label :actions %>
	<%=b.text_field :action , required:true%>

<td><%= b.submit "Create" , class:"btn btn-primary"%></td>
	<%end%>


<table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Roles</th>
                    <th></th>

                    <th>Action</th>

                	</tr>
					<% UserRole.all.each do |role|%>
                  <tr>
					<td><%= role.name %></td>
					<td></td>

					<td><%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  role_destroy_users_users_path(id: role.id), class:"btn btn-danger"  ,title: "Delete" %> </td>
					</tr>
					
					<%end%>


<tr style="background-color: #DDD7D6">
                   
                    <th>Menus</th>
                    <th>Actions</th>
                    <th></th>

</tr>
					<% Menu.all.order('created_at ASC').first(3).each do |menu|%>
					<tr>
					<td><%= menu.menu%></td>

					<td><%= menu.actions.pluck(:action).join(', ') %></td>
					<td><%#= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  	menu_destroy_admins_admins_path(id: menu.id), class:"btn btn-danger"  ,title: "Delete" %> </td>

					
					</tr>
					<%end%>
</table>





<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script type="text/javascript">

 function myFunction(input){
 	debugger;
 var menu_id = input.elements[2].value;

   
     if(menu_id == "")
     {
		alert("plz select the menu the first");
		return false;
	}
}

	
</script>

app/views/users/users/users.html.erb
    <h1>Profile</h1>
    <%= link_to '<em class="btn fa fa-plus-circle" aria-hidden="true"></em><span style="font-size:15px">Add New User</style>'.html_safe,  create_user_users_users_path, class:"btn btn-sm btn-primary" ,title: "Add User", style: "float:right;margin-top:-50px" %>
<p class="box box-primary"></p>



 

<div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Name</th>
					<th>Email</th>
				<!-- 	<th>Profile</th> -->
					<th>Phone</th>
					<th>Role</th>
					<th >Action</th>
					
                  </tr>
                    <%#@users = [] unless @users.present?%>
					<% @users.each do |user| %>
					<% unless user.eql?(nil) %>
                  <tr>
					<td><%= user&.name %></td>
					<td><%= user&.email%></td>
					<td><%= user&.phone%></td>
					<td><%= user&.user_role&.name%></td>
					

					<td>
      						<%# binding.pry %>
         				<% if return_action_id("View") %>
						<%= link_to '<em class="fa fa-eye" aria-hidden="true"></em>'.html_safe,  user_view_users_users_path(id:user.id), class: "btn btn-success"  ,title: "show" %>
  						
         				
  						<% end %>

         				<% if return_action_id("Block") %>
						

						<%if user.status.present?  %>

					
					<%= link_to '<em class="fa  fa-unlock" aria-hidden="true"></em>'.html_safe,  block_users_users_path(id: user.id), class:"btn btn-success" ,title: "Unblock" %>
					
					<% else %>

					<%= link_to '<em class="fa fa-ban" aria-hidden="true"></em>'.html_safe,  block_users_users_path(id: user.id), class:"btn btn-warning" ,title: "Block" %>
					
		
					
					 <%end%>	
  						<% end %>

          				<% if return_action_id("Delete") %>

						<%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  user_destroy_users_users_path(id: user.id), class: "btn btn-danger" ,title: "Delete" %>
     					<%end%>
     				</td>

					</tr>	
					<%end%>
                


<%end%>


</table>
<%= will_paginate @users %>

</div>