config/routes.rb
 

  

  Rails.application.routes.draw do


    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'

    mount Ckeditor::Engine => '/ckeditor'
   
   get 'login', to: redirect('/auth/google_oauth2')
   get 'login' , to: redirect('/auth/github')
   get 'logout', to: 'sessions#destroy'
   get 'auth/:provider/callback', to: 'users/sessions#create_admin'
   get '/auth/github/callback' , to:'users/sessions#create_admin'
   get '/auth/facebook/callback' , to:'users/sessions#create_admin'
   get 'auth/failure', to: redirect('/')
      get 'password_resets/new'
  get 'password_resets/edit'


   root 'sessions#new'
   resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]



    namespace :api do 
      namespace :v1 do
        resources :sessions do
          collection do
            post :show_all_user 
            post :otp_admin
            post :create_users
            post :user_view
            delete :user_destroy
            post :block
            post :user_role_create
            post :user_role_update
            post :show_role
            delete :role_destroy
            post :content_create
            post :show_content
            delete :content_destroy
            post :create_action
            post :show_menu
            post :permission_management
            post :show_all_permission
            delete :permission_destroy
          end
        end
      end
    end




namespace :admins do 
  resources :admins do
    collection do
      post :user_role_update
      get :dashboard
      get :users
      get :static_content
      post :content_create
      get :show_content
      get :user_view
      get :block
      get :user_destroy
      get :content_destroy
      get :create_user
      post :create_users
      get :user_role
      post :user_role_create
      post :user_permission_create
      get :permission_management
      post :return_actions
      post :save_permission
      get :permission_destroy
      get :role_destroy
      get :menu_destroy
      get :content_edit
      post :content_update
      post :check_action
      post :check_menus_action
      
     end
    end
 resources :sessions do
      collection do
       get :otp
       get :destroy
       post :otp_admin
       get :signout
      end
    end 
end


namespace :users do 
  resources :users do
    collection do 
     get :dashboard
     get :show
     get :destroy
     post :check_email
     get :dashboard
      get :users
      get :static_content
      post :content_create
      get :show_content
      get :user_view
      get :block
      get :user_destroy
      get :content_destroy
      get :create_user
      post :create_users
      get :user_role
      post :user_role_create
      post :user_permission_create
      get :permission_management
      post :return_actions
      post :save_permission
      get :permission_destroy
      get :role_destroy
      get :menu_destroy
      get :content_edit
      post :content_update
      post :check_action
      post :check_menus_action


     end
    end

      resources :sessions do
      collection do
       post :otp
       post :otp_user
       get :destroy
      end
    end
    resources :password_resets do
      collection do
        post :create
        get :new
        get :edit
      end
    end
  end



end
     
   

app/views/admins/admins/content_edit.html.erb
<h1>Static Content Management</h1>

<p class="box box-primary"></p>



<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>

	<%=  form_for :content, url: content_update_admins_admins_path(id: @content.id) ,method: :post, local: true do |b| %>
   <%= b.label :Title %> 
   <%= b.text_field :title , value: @content.title%><br><br> 
  

   <%= b.label :Content %> 
<%= b.text_area :latest_content, :class => 'ckeditor' , value: @content.latest_content%><br>
   <%= b.label :"Start Date" %> 
   &nbsp;

  <%= b.date_field :start_date ,value: @content&.start_date && l(@content&.start_date&.to_date) %>

  <%= b.label :"End Date"  , style: "margin: 0 0 0 400px;"%>
  
  <%= b.date_field :end_date , value: @content&.end_date && l(@content&.end_date&.to_date ) , style: "margin: 0 0 0 20px;" %><br>


	<%= b.submit :save ,class:"btn btn-success",  style: "margin: 0px 0px -200px 500px;" %>
<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  show_content_admins_admins_path, class:"btn btn-primary"  ,title: "Back"  ,  style: "margin: 0px 0px -200px 50px;" %>
	<%end%>



    

app/views/admins/admins/create_user.html.erb
<h1>Add User</h1>

<%= flash[:notice] %>

<%= form_with scope: :user, url: create_users_admins_admins_path,:html=>{id: "first"},local: true  do |form| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



 <p>
    <%= form.label :Name %>
    <%= form.text_field :name ,placeholder: 'Your name here' %>
  </p>
 
 <p>
    <%= form.label :Email %>
    <%= form.email_field  :email ,placeholder: 'Your email here'%>
 
  </p>
 
<p>
    <%= form.label :Phone %>
    <%= form.text_field  :phone , placeholder: 'Your phone here'%>
 
  </p>
 


<p>
   <%= form.label :password %>
<%= form.password_field :password %>
</p>

<p>
   <%= form.label :Confirm_password %>
<%= form.password_field :password_confirmation %>
</p>


<p>
   <%= form.label :Role %>

  <%= form.collection_select :user_role_id, UserRole.order(:name), :id, :name,   include_blank: true %>
</p>

<p>
   <%= form.label :Profile %>
<%= form.file_field :avatar ,onchange: "readURL(this);"%>
</p>
 <div>
 <img id="blah" />
</div>


  <p>
    <%= form.submit "Signup"%>
  </p>

  <%end%>

<script type="text/javascript">

function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(150);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script> 
<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  users_admins_admins_path, class:"btn btn-primary"  ,title: "Back" %>

app/views/admins/admins/dashboard.html.erb
 <h1>Dashboard</h1>
<p class="box box-primary"></p>

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="/assets/3909726.png"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center"><%=@admin&.email%></h3>

                <p class="text-muted text-center">Software Engineer</p>

                
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fa fa-book"></i> Education</strong>

                <p class="text-muted">
                  B.S. in Computer Science from the University of Tennessee at Knoxville
                </p>

                <hr>

                <strong><i class="fas fa fa-map-marker"></i> Location</strong>

                <p class="text-muted">Malibu, California</p>

                <hr>

                <strong><i class="fa fa-pencil"></i> Skills</strong>

                <p class="text-muted">
                  <span class="btn btn-primary">Ruby on Rails</span>
                  <span class="btn btn-success">Coding</span>
                  <span class="btn btn-danger">Javascript</span>
                  
                </p>

                <hr>

                <strong><i class="fa fa-file-text-o"></i> Notes</strong>

                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

app/views/admins/admins/permission_management.html.erb
 <style type="text/css">
   .my-popup .modal-content {
      background: #1eaace;
color: white;
}
 </style>



  <h1>Permission Management</h1>
<p class="box box-primary"></p>


 <%=  form_for :permission,html: { onsubmit: "return myFunction1(this);" }, url: save_permission_admins_admins_path ,method: :post, local: true do |b| %>


<%= b.label :Role %>
<%= b.collection_select :role, UserRole.all, :id, :name,  :prompt => 'Select',required: true %>

<%= b.label :menu %>
<%= b.select(:menus, Menu.all.order('created_at ASC').first(3).collect {|m| [m.menu, m.id]},{prompt: "Select"},{onchange: "myFunction(this);"}) %>



<%= b.label :action %>
<%= b.select :action, options_for_select([]),:prompt => 'Select' 	%>

<td><%= b.submit "Save" , class:"btn btn-primary"%></td>

<%end%>



 <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Role</th>
					<th>Menu</th>
				<!-- 	<th>Profile</th> -->
					<th>Actions</th>
					<th></th>

                  </tr>
                  <tr>
                    <%#@contents = [] unless @contents.present?%>

					<% Permission.all.each do |permission|%>
          <%#binding.pry%>
          <% unless permission.eql?(nil) %>
          <td><%= UserRole.find_by(id:permission&.user_role_id)&.name%></td>
          <td><%= Menu.find_by(id:permission&.menu_id)&.menu%></td>
          <td><%= permission&.permission%></td>
           
          
          
<td><%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  permission_destroy_admins_admins_path(id: permission.id), class:"btn btn-danger"  ,title: "Delete" %> </td>
					</tr>
                


<%end%>
<%end%>


</table>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://github.com/makeusabrew/bootbox/releases/download/v4.4.0/bootbox.min.js"></script>

<script type="text/javascript">
  $('#session_menu_id').change(myFunction);
 function myFunction(input){
debugger;
 var menu_id = input.value;
 code = {code: menu_id}
   
     if(menu_id == "")
     {
       $('#permission_action').empty();
     }
     else
     {
 $.ajax(
   {
     type: 'POST',
     url: "/admins/admins/return_actions",
     data: code,
     success: function(result){
       var new_options = result;
       var menuaction = $('#permission_action').empty();
   $.each(new_options, function(key,values) {
     $.each(values, function(index,value) {
     menuaction.append($("<option></option>").attr("value", value).text(value));
   });
   });

  // alert ("ffcng");
   }
});
}
 }
</script>



<script type="text/javascript">
// debugger;
function myFunction1(input){
 	debugger;
 var role = input.elements[2].value;
 var menu = input.elements[3].value;
 var action = input.elements[4].value;
 actions = {actions: action}
 menus = {menus: menu}
 roles = {roles: role,actions: action,menus: menu}

       if((role == "") || (menu == "") || (action == ""))
     {
		bootbox.alert({
     title: 'Alert!',
     message: "Please select all the fields",
     className: "my-popup"
  });
		return false;
	}
  else
  {
    $.ajax({
  url: '/admins/admins/check_action',
  method: 'POST',
  data: roles,
    success: function(response){
      debugger;
    if(response && response.message=='ERROR'){
        bootbox.alert({
     title: 'Alert',
     message: "Permission already exists",
     className: "my-popup"
  });
    }
    else
    {
      
       // if (data.success == true)
    window.location = window.location; 
    
    }
}
});
        return false;

  }
}

	
</script>

app/views/admins/admins/show_content.html.erb
<h1>Static Content Management</h1>
<%= link_to '<em class="btn fa fa-plus-circle" aria-hidden="true"></em><span style="font-size:15px">Add New Content</style>'.html_safe,  static_content_admins_admins_path, class:"btn btn-sm btn-primary" ,title: "Add Content", style: "float:right;margin-top:-50px" %>
<p class="box box-primary"></p>



 

<div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Title</th>
					<th>Content</th>
				<!-- 	<th>Profile</th> -->
					<th>Start Date</th>
					<th>End Date</th>
					<th>Action</th>

					
                  </tr>
                  <tr>
                    <%#@contents = [] unless @contents.present?%>

					<% @contents.each do |content|%>
					<% unless content.eql?(nil) %>
					<td><%= content.title %></td>
					<td><%= content.latest_content.html_safe%></td>
					<td><%= content.start_date%></td>
					<td><%= content.end_date%></td>

<td><%= link_to '<em class="fa  fa-edit" aria-hidden="true"></em>'.html_safe,  content_edit_admins_admins_path(id: content.id), class:"btn btn-primary"  ,title: "Edit" %> 
				


<%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  content_destroy_admins_admins_path(id: content.id), class:"btn btn-danger"  ,title: "Delete" %></td> 
                



					</tr>


<%end%>
<%end%>


</table>
<%= will_paginate @contents %>

</div>

app/views/admins/admins/static_content.html.erb
 <style type="text/css">
   .my-popup .modal-content {
      background: #1eaace;
color: white;
}
 </style>




<h1>Static Content Management</h1>

<p class="box box-primary"></p>



<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>

	<%=  form_for :session, html: { onsubmit: "return myFunction(this);" },url: content_create_admins_admins_path ,method: :post, local: true do |b| %>
   <%= b.label :Title %> 
   <%= b.text_field :title,required:true %><br><br> 
  

   <%= b.label :Content %> 
<%= b.text_area :latest_content, :class => 'ckeditor' %><br>
   <%= b.label :"Start Date" %> 
   &nbsp;
   <%= b.date_field :start_date , required:true%>
  <%= b.label :"End Date"  , style: "margin: 0 0 0 400px;"%>
	<%= b.date_field :end_date , style: "margin: 0 0 0 20px;",required:true %><br>

	<%= b.submit :save ,class:"btn btn-success",  style: "margin: 0px 0px -200px 500px;" %>
<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  show_content_admins_admins_path, class:"btn btn-primary"  ,title: "Back"  ,  style: "margin: 0px 0px -200px 50px;" %>
	<%end%>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://github.com/makeusabrew/bootbox/releases/download/v4.4.0/bootbox.min.js"></script>
<script type="text/javascript">

 function myFunction(input){
  debugger;
 var ckeditor = input.elements[3].value;

   
     if(ckeditor == "")
     {
    bootbox.alert({
     title: 'Alert!',
     message: "Please fill the content",
     className: "my-popup"
  });
    return false;
  }
}

  
</script>

app/views/admins/admins/user_role.html.erb
<h1>Create Role</h1>
<p class="box box-primary"></p>

<%=  form_for :session, url: user_role_create_admins_admins_path ,method: :post, local: true do |b| %>
	
    <%= b.label :Role %>

	<%=b.text_field :name , required:true%>
				
 <%#= b.label :Menu %>
<%#=b.text_field :menu %>

	<td><%= b.submit "Create" , class:"btn btn-primary"%></td>


	<%end%>

<!-- <h1>Create Actions for each menu</h1>
<p class="box box-primary"></p>

<%#=  form_for :session,html: { onsubmit: "return myFunction(this);" }, url: user_permission_create_admins_admins_path ,method: :post, local: true do |b| %>

    <%#= b.label :Menu %>

<%#= b.collection_select :menu_id, Menu.all.order('created_at ASC').first(3), :id, :menu, {:include_blank => '-select-'}%>

    <%#= b.label :actions %>
	<%#=b.text_field :action , required:true%>

<td><%#= b.submit "Create" , class:"btn btn-primary"%></td>
	<%#end%> -->


<table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Roles</th>
                    <th></th>

                    <th>Action</th>

                	</tr>
					<% UserRole.all.each do |role|%>
                  <tr>
					<td><%= role.name %></td>
					<td></td>

					<td><%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  role_destroy_admins_admins_path(id: role.id), class:"btn btn-danger"  ,title: "Delete" %> </td>
					</tr>
					
					<%end%>
</table>

<!-- 
<tr style="background-color: #DDD7D6">
                   
                    <th>Menus</th>
                    <th>Actions</th>
                    <th></th>

</tr>
					<%# Menu.all.order('created_at ASC').first(3).each do |menu|%>
					<tr>
					<td><%#= menu.menu%></td>

					<td><%#= menu.actions.pluck(:action).join(', ') %></td>
					<td><%#= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  	menu_destroy_admins_admins_path(id: menu.id), class:"btn btn-danger"  ,title: "Delete" %> </td>

					
					</tr>
					<%#end%>





<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script type="text/javascript">

 function myFunction(input){
 	debugger;
 const menu_id = input.elements[2].value;
 var action = input.elements[3].value
 menus = {menus: menu_id, actions: action}

   
     if(menu_id == "")
     {
		alert("plz select the menu the first");
		return false;
	}

else 
{
    	debugger;
    $.ajax({
  url: '/admins/admins/check_menus_action',
  method: 'POST',
  data: menus,
    success: function(response){
    if(response && response.message =='ERROR'){
        alert(" "+response.action+" for "+response.value+" already exists");
    	 return; 

    }
    // else
    // {
    // 	return true;

    // }


}
});
        return false;

  }
  
}
	
</script>

app/views/admins/admins/user_view.html.erb
<h1>Profile</h1>


<div>

<p>
  <strong>Name:</strong>
  <%= @user&.name %>
</p>
 
 <p>
	<strong>Email:</strong>
	<%=@user&.email%>
</p>

<p>
	<strong>Phone:</strong>
	<%=@user&.phone%>
</p>

<p>
	<strong>Role:</strong>
	<%=@user&.user_role&.name%>
</p>

<p>
  <strong>Image:</strong>
 
   <%= image_tag @user&.avatar&.url %>
</p>

<%= link_to '<em class="fa  fa-mail-reply-all" aria-hidden="true"></em>'.html_safe,  users_admins_admins_path, class:"btn btn-primary"  ,title: "Back" %>

app/views/admins/admins/users.html.erb
<style type="text/css">
.pagination {
  display: inline-block;
}
	.pagination a {
  border-radius: 5px;
}

.pagination a.active {
  border-radius: 5px;
}
.next_page{
  border-radius: 5px !important;

}
   .my-popup .modal-content {
      background: #1eaace;
color: white;
}
</style>






    <h1>Profile</h1>
    <%= link_to '<em class="btn fa fa-plus-circle" aria-hidden="true"></em><span style="font-size:15px">Add New User</style>'.html_safe,  create_user_admins_admins_path, class:"btn btn-sm btn-primary" ,title: "Add User", style: "float:right;margin-top:-50px" %>
<p class="box box-primary"></p>



 

<div class="card-body table-responsive p-0" , id ="example2_paginate">
                <table class="table table-hover">
                  <tr style="background-color: #DDD7D6">
                    <th>Name</th>
					<th>Email</th>
				<!-- 	<th>Profile</th> -->
					<th>Phone</th>
					<th>Role</th>
					<th >Action</th>
					<th>Change Role</th>
					<th>Save</th>

					
                  </tr>
                  <tr>
                    <%#@users = [] unless @users.present?%>
					<% @users.each do |user|%>
					<% unless user.eql?(nil) %>
					<td><%= user&.name %></td>
					<td><%= user&.email%></td>
					<td><%= user&.phone%></td>
					<td><%= user&.user_role&.name%></td>
					

					<td><%= link_to '<em class="fa fa-eye" aria-hidden="true"></em>'.html_safe,  user_view_admins_admins_path(id: CGI.escape(user.id.to_s)), class:"btn btn-success"  ,title: "show" %> 


					<%if user.status.present?  %>

					
					<%= link_to '<em class="fa  fa-unlock" aria-hidden="true"></em>'.html_safe,  block_admins_admins_path(id: user.id), class:"btn btn-success" ,title: "Unblock" %>
					
					<% else %>

					<%= link_to '<em class="fa fa-ban" aria-hidden="true"></em>'.html_safe,  block_admins_admins_path(id: user.id), class:"btn btn-warning" ,title: "Block" %>
					
		
					
					 <%end%>	


					<%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  user_destroy_admins_admins_path(id: user.id), class:"btn btn-danger" ,title: "Delete" %></td>



				


					 <%=  form_for :session,html: { onsubmit: "return myFunction(this);" }, url: user_role_update_admins_admins_path(id: user.id) ,method: :post, local: true do |b| %>
					<td><%= b.collection_select :user_role_id, UserRole.all, :id, :name,   :prompt => 'Select'  %></td>
					
					<td><%= b.submit "Save" , class:"btn btn-primary"%></td>

					<%end%>
<%#= select_tag 'user_role_id', options_for_select(UserRole.all.collect{ |c| [c.name,  c.id]}) %>

					<!-- <td><%= user.user_role_id %></td> -->

					</tr>	
					<%end%>
                


<%end%>


</table>
<%= will_paginate @users %>

</div>

 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://github.com/makeusabrew/bootbox/releases/download/v4.4.0/bootbox.min.js"></script>
<script type="text/javascript">

 function myFunction(input){
 	// debugger;
 var menu_id = input.elements[2].value;

   
     if(menu_id == "")
     {
		bootbox.alert({
     title: 'Alert!',
     message: "Please select Role first",
     className: "my-popup"
  });
		return false;
	}
}

	
</script>